# Generated by Django 5.2.5 on 2025-08-28 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_department_alter_manager_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
