# Generated by Django 5.2.5 on 2025-08-29 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_manager_joined_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
